-- 1. Criação das tabelas principais (Categories e Products)
-- O tipo NUMERIC(10,2) substitui o REAL do SQLite para garantir precisão financeira exata, sem erros de arredondamento de ponto flutuante.

CREATE TABLE IF NOT EXISTS public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS public.products (
    id bigint generated by default as identity primary key,
    external_id text,
    barcode text, -- Mantido como texto para preservar zeros à esquerda
    name text not null,
    description text,
    category_id bigint references public.categories(id) on delete set null,
    brand text,
    price numeric(10,2) default 0,
    old_price numeric(10,2),
    stock integer default 0,
    image_url text,
    active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Sistema de Permissões Isolado e Seguro
-- Essa tabela não pode ser manipulada por usuários comuns.
CREATE TABLE IF NOT EXISTS public.admins (
    user_id uuid references auth.users(id) on delete cascade primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Função de segurança blindada para verificar se quem está logado é administrador.
-- SECURITY DEFINER permite que a função olhe a tabela 'admins' internamente.
-- SET search_path = public impede ataques de sequestro de schema.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Revogar execução pública da função e garantir que só usuários autenticados possam rodá-la (ou o banco).
REVOKE EXECUTE ON FUNCTION public.is_admin FROM public;
GRANT EXECUTE ON FUNCTION public.is_admin TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin TO service_role;

-- 3. Ativação do Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Como a tabela 'admins' está com RLS ligado e NÃO há nenhuma política nela,
-- por padrão do Postgres, apenas o Service Role (Backend Master) ou o dono do banco podem manipulá-la.
-- Usuários autenticados não podem fazer SELECT, INSERT, UPDATE ou DELETE nela diretamente.

-- 4. Trigger de Automação para updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- 5. Políticas da Tabela Categorias
-- Leitura pública apenas se a categoria estiver ativa (ou se quem acessa for admin).
CREATE POLICY "Categorias ativas visíveis ao público, inativas só para admins" ON public.categories 
FOR SELECT USING (active = true OR public.is_admin());

-- Modificação apenas por admins (com CHECK para UPDATE garantindo a mesma restrição)
CREATE POLICY "Admins podem inserir categorias" ON public.categories FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admins podem atualizar categorias" ON public.categories FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins podem deletar categorias" ON public.categories FOR DELETE USING (public.is_admin());

-- 6. Políticas da Tabela Produtos
-- Leitura pública apenas para produtos ativos. Produtos ocultos só podem ser lidos por admins.
CREATE POLICY "Produtos ativos são visíveis ao público, inativos só para admins" ON public.products FOR SELECT USING (
    active = true OR public.is_admin()
);
-- Modificação apenas por admins
CREATE POLICY "Admins podem inserir produtos" ON public.products FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admins podem atualizar produtos" ON public.products FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins podem deletar produtos" ON public.products FOR DELETE USING (public.is_admin());

-- 7. Índices recomendados para otimizar busca textual e carregamento
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products (name);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_barcode ON public.products (barcode);
